### ISSUE TITLE
Under Ubuntu 20.04 amd, trying to  compile latest from source, the unit 'dom' cannot be found

### ISSUE THREAD

**Issue by wglb** [trlinux/trlinux#1]
In the file scorereporter.pas, the line

    uses sysutils,dom,xmlwrite,logcfg,tree,logedit,logdupe,logwind,logdom,logstuff;

fails on the unit 'dom' and 'xmlwrite' that don't seem to be part of the source tree.

**Comment by geoiii** [comment]
I compiled the latest source on a raspberry pi yesterday without issue.  Not sure what would be missing. 

Is there a reason you are compiling for this OS?  The binary release should work I would think. 

George Fremin III

**Comment by w9cf** [comment]
Those units are in the free component library distributed with the free pascal compiler.
https://www.freepascal.org/fcl/fcl.html#:~:text=The%20FCL%20is%20maintained%20by,be%20seen%20as%20a%20restriction.

The release versions of the code which have the binary releases here on github are compiled with github runners which are running Ubuntu 20.04 LTS. On my Slackware machine those fcl units are with the other units
in /usr/lib64/fpc/3.2.2/units/x86_64-linux/fcl-xml but other distributions may put those files in another place.

73 Kevin w9cf

**Comment by wglb** [comment]
geoiii: I was thinking of doing some minor mods.

Kevin: That is the trick--ubuntu puts them off into different directory so I added

    -Fu/usr/share/fpcsrc/3.0.4/packages/fcl-xml/src/ 

to the build for trlog in the Makefile. Also needed to make that directory writeable.

**Comment by wglb** [comment]
To clarify what I added to the .fpc.cfg file, here are the contents

    #INCLUDE /etc/fpc.cfg
    -Fl/usr/lib/gcc/arm-linux-gnueabihf/8
    -Fu/usr/share/fpcsrc/3.0.4/packages/fcl-xml/src/
    -Fu/usr/share/fpcsrc/3.0.4/packages/fcl-base/src/
    -Fu/usr/share/fpcsrc/3.0.4/packages/libcurl/src/

This is for Ubuntu 20.04.
