### ISSUE TITLE
*.DOM files missing from source repo

### ISSUE THREAD

**Issue by dslotter** [trlinux/trlinux#9]
trlog complains shortly after startup that "ARRLSECT.DOM" is missing when I select "Field Day".

This file is not to be found in the git repo, but I can find it in the releases.

Please have **all** sources and config files needed to run the program in the git repo, or point the third-party developer where to retrieve them, please.

**Comment by geoiii** [comment]
They should be in there. If they exist in the release it should be in the src since they are built from the repo with GitHub actions. I will look into it. Thanks for the report.  George Fremin IIIOn Sep 18, 2022, at 9:17 PM, Dave Slotter ***@***.***> wrote:﻿
trlog complains shortly after startup that "ARRLSECT.DOM" is missing when I select "Field Day".
This file is not to be found in the git repo, but I can find it in the releases.
Please have all sources and config files needed to run the program in the git repo, or point the third-party developer where to retrieve them, please.

**Comment by dslotter** [comment]
Hi @geoiii . When I search https://github.com/trlinux/trlinux/search?q=ARRLSECT.DOM , I find three source code results, but no actual files. This is easy enough to reproduce. :-)

**Comment by geoiii** [comment]
I am not saying it is not true just that it is very odd and hard for me to understand how. But is easy to correct.  I have not gotten to a real computer yet but will check it out. George Fremin IIIOn Sep 19, 2022, at 7:59 AM, Dave Slotter ***@***.***> wrote:﻿
Hi @geoiii . When I search https://github.com/trlinux/trlinux/search?q=ARRLSECT.DOM , I find three source code results, but no actual files. This is easy enough to reproduce. :-)

**Comment by w9cf** [comment]
Dave,
The search you give does not show the file. However, I see the file in https://github.com/trlinux/trlinux/tree/master/log
where it should be.  Can you verify the result of:

git clone https://github.com/trlinux/trlinux.git
find trlinux -name ARRLSECT.DOM

On my computer I get:

trlinux/log/ARRLSECT.DOM

73 Kevin w9cf

**Comment by geoiii** [comment]
Dave, 

I was just going to say the same thing that Kevin did - can you help me understand how you set things up and how you started trlog such that did can not find the DOM file?

**Comment by dslotter** [comment]
Kevin,

Oh my! You are absolutely right! Apparently the GitHub search only looks inside files and not for file names.

We can close this as invalid. Sorry for wasting your time.

-Dave, W3DJS

**Comment by dslotter** [comment]
@geoiii I ran trlog out of the src directory -- and of course the files it needs are in the log directory.

**Comment by geoiii** [comment]
Did you do a build from source?
And you did that inside the src dir?
And then trlog exists in src? 

That is my guess

There is a makefile one level up that builds things and then copies trlog into locations that make it able to fine the dom files.

**Comment by w9cf** [comment]
Dave,
The search you give does not show the file. However, I see the file
in https://github.com/trlinux/trlinux/tree/master/log
where it should be.  Can you verify the result of:

git clone https://github.com/trlinux/trlinux.git
find trlinux -name ARRLSECT.DOM

On my computer I get:

trlinux/log/ARRLSECT.DOM

73 Kevin w9cf
